#!/usr/bin/env python3
"""
Module: Asynchronous list comprehension
"""
from typing import List

async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """
    Asynchronous list comprehension that returns a list of floats
    generated by the async_generator function.

    Returns:
        List[float]: a list of floats generated by the async_generator.
    """
    return [async_list async for async_list in async_generator()]
